# Generated by Django 5.2.8 on 2025-11-16 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("min_aqi", models.IntegerField()),
                ("max_aqi", models.IntegerField()),
                ("message", models.TextField()),
                ("recommendations", models.TextField()),
            ],
            options={
                "ordering": ["min_aqi"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("source", models.CharField(max_length=256)),
                ("url", models.URLField(unique=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.TextField()),
                ("raw_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("mask", "Mask"),
                            ("purifier", "Air Purifier"),
                            ("monitor", "Air Quality Monitor"),
                            ("car-filter", "Car Filter"),
                            ("plant", "Plant"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("product_url", models.URLField(blank=True, null=True)),
                ("aqi_min", models.IntegerField(default=0)),
                ("aqi_max", models.IntegerField(default=500)),
                ("effectiveness", models.IntegerField(default=0)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews", models.IntegerField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, default=list)),
                ("recommended_for", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product_type", "-effectiveness"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("state", models.CharField(blank=True, max_length=128, null=True)),
                ("country", models.CharField(default="India", max_length=128)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("population", models.IntegerField(blank=True, null=True)),
                ("station_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="aqi_app_cit_name_e2beb0_idx"),
                    models.Index(fields=["state"], name="aqi_app_cit_state_bcb9cf_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "data_source",
                    models.CharField(
                        default="OpenAQ",
                        help_text="API or dataset used to fetch data",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="aqi_app.city",
                    ),
                ),
            ],
            options={
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="TravelRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=256)),
                ("source_lat", models.FloatField()),
                ("source_lon", models.FloatField()),
                ("dest_name", models.CharField(max_length=256)),
                ("dest_lat", models.FloatField()),
                ("dest_lon", models.FloatField()),
                ("route_geometry", models.JSONField()),
                ("pollution_score", models.FloatField()),
                ("average_aqi", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="aqi_app.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("conditions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preferred_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="aqi_app.city",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("target_time", models.DateTimeField(db_index=True)),
                ("predicted_aqi", models.FloatField()),
                ("model_name", models.CharField(max_length=64)),
                ("model_version", models.CharField(default="v1", max_length=32)),
                ("confidence_low", models.FloatField(blank=True, null=True)),
                ("confidence_high", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="aqi_app.city",
                    ),
                ),
            ],
            options={
                "ordering": ["target_time"],
                "unique_together": {("city", "target_time", "model_name")},
            },
        ),
        migrations.CreateModel(
            name="AQIReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("aqi", models.IntegerField(blank=True, null=True)),
                ("pm25", models.FloatField(blank=True, null=True)),
                ("pm10", models.FloatField(blank=True, null=True)),
                ("no2", models.FloatField(blank=True, null=True)),
                ("so2", models.FloatField(blank=True, null=True)),
                ("o3", models.FloatField(blank=True, null=True)),
                ("co", models.FloatField(blank=True, null=True)),
                ("nh3", models.FloatField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="aqi_app.city",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="aqi_app.station",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="aqi_app_aqi_timesta_fc290d_idx"
                    ),
                    models.Index(fields=["aqi"], name="aqi_app_aqi_aqi_8aa478_idx"),
                    models.Index(fields=["pm25"], name="aqi_app_aqi_pm25_e38775_idx"),
                ],
                "unique_together": {("station", "timestamp")},
            },
        ),
    ]
